<template>
  <div class="main">
    <div class="guide-text">Only xml files generated by EA with UML 1.1 is supported.</div>
  <el-upload
    class="upload-demo"
    action="https://jsonplaceholder.typicode.com/posts/"
    :on-preview="handlePreview"
    :on-remove="handleRemove"
    :before-remove="beforeRemove"
    :before-upload="beforeUpload"
    :limit="1"
    :auto-upload="false"
    ref="upload"
    >

    <el-button style="margin-right: 10px" size="medium" type="success" >Upload</el-button>
    <el-button size="medium" type="primary"  @click="submitUpload">Submit</el-button>
  </el-upload>

  </div>
</template>
<script>
  export default{
    data(){
      return{
        fileList: []
      }
    },
    mounted(){
      this.$emit('step',0);
    },
    methods: {
      handleRemove(file, fileList) {
        console.log(file, fileList);
      },
      handlePreview(file) {
        console.log(file);
      },

      beforeRemove(file, fileList) {
        //return this.$confirm(`Cancel the transfert of ${ file.name } ?`);
      },
      submitUpload() {
        this.$refs.upload.submit();
        this.$router.push('/reconstruct/original-structure')
      },
      beforeUpload(file){
        let name=file.name
        if(name.toString().endsWith('.xml')){return true;}
        else{
          this.$alert("Not supported File"); return false;
        }
      }
    }
  }
</script>
<style scoped>
  .main{
    float:left;
    margin:20px;
    padding:20px;
  }
  .guide-text{
    margin-bottom: 20px;
  }
</style>
