<template>
  <div class="main">
    <div class="guide-text">Only file with UML 1.1 specification is supported, which is generated by EA.</div>
    <el-upload
      class="upload-demo"
      action="https://no-use-at-all"
      :on-preview="handlePreview"
      :on-remove="handleRemove"
      :before-remove="beforeRemove"
      :before-upload="beforeUpload"
      multiple
      :limit="1"
      :on-exceed="handleExceed"
      :file-list="fileList">
      <el-button size="small" type="primary" >Upload</el-button>

    </el-upload>
    <el-button size="small" @click="submitFile">Submit</el-button>

  </div>
</template>
<script>
  import Qs from 'qs'
  export default{
    data(){
      return{
        fileList: []
      }
    },
    mounted(){
      this.$emit('step',0);
    },
    methods: {
      handleRemove(file, fileList) {
        console.log(file, fileList);
      },
      handlePreview(file) {
        console.log(file);
      },
      beforeRemove(file, fileList) {
        //return this.$confirm(`Cancel the transfert of ${ file.name } ?`);
      },
      handleExceed(files, fileList){
        this.$message({message:'Only one file can be uploaded. Please delete the original file.',duration:1000})
      },
      beforeUpload(file){
        let _this=this;
        console.log(file)
        let name=file.name
        this.fileList.push(file)
        console.log(name)
        if(name.toString().endsWith('.xml')){return true;}
        else{
          this.$message.error("Not supported File");
          // _this.fileList=f.slice(0,0);
          return false;

        }
      },



      submitFile() {
        let _this=this;
        // this.$confirm(_this.fileList.toString());


        // var data = Qs.stringify(_this.fileList);
        console.log(_this.fileList[0]);
        var formData = new FormData();
        formData.append("file",_this.fileList[0]);
        // formData.append("operatorId", operatorId);

        var ret=null;
        this.$http.post(this.baseUrl+'fileUpload', formData,
          {headers:{'Content-Type':'application/x-www-form-urlencoded', 'dataType': 'json'}})
          .then((res)=>{

            console.log(res.data.name)
            ret=res.data
            _this.$router.push({
              name: "original",
              params: {
                tag: ret.tag,
                matrix: ret.matrix,
                fname: ret.name,
                fileData: _this.fileList[0]
              }
            })
          })

      }

    }
  }
</script>
<style scoped>
  .main{
    float:left;
    margin:20px;
    padding:20px;
  }
  .guide-text{
    margin-bottom: 20px;
  }
</style>
